"""
Panoramic 3DGS renderer.

Two rendering paths are provided:
  - render_panoramic(): classic cubemap-based path (6 pinhole faces 鈫?ERP stitch).
  - render_erp_direct(): direct ERP path using GaussianRasterizerERP, which
    supports analytical SE(3) pose gradients and radial depth gradients.

render_erp_direct() is the preferred path for SLAM: it is faster (one kernel
instead of six), supports cam_rot_delta / cam_trans_delta gradient flow, and
correctly handles the ERP seam and full-sphere visibility.
"""

from functools import lru_cache
from typing import List, Optional

import numpy as np
import torch
import torch.nn.functional as F

from backend.legacy_360gs.gaussian_splatting.gaussian_renderer import render
from backend.legacy_360gs.utils.camera_utils import FaceCamera


_CUBEMAP_RS = np.array(
    [
        [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        [[0, 0, -1], [0, 1, 0], [1, 0, 0]],
        [[-1, 0, 0], [0, 1, 0], [0, 0, -1]],
        [[0, 0, 1], [0, 1, 0], [-1, 0, 0]],
        [[1, 0, 0], [0, 0, 1], [0, -1, 0]],
        [[1, 0, 0], [0, 0, -1], [0, 1, 0]],
    ],
    dtype=np.float32,
)


def _build_face_camera(body_cam, face_idx: int) -> FaceCamera:
    r_local = torch.tensor(_CUBEMAP_RS[face_idx], dtype=torch.float32, device=body_cam.device)
    r_face = r_local @ body_cam.R.to(dtype=r_local.dtype)
    t_face = r_local @ body_cam.T.to(dtype=r_local.dtype)
    face_image = None
    if getattr(body_cam, "face_images", None) is not None and face_idx < len(body_cam.face_images):
        face_image = body_cam.face_images[face_idx]

    return FaceCamera(
        R=r_face,
        T=t_face,
        face_image=face_image,
        projection_matrix=body_cam._face_proj_mat,
        face_w=body_cam.face_w,
        body_cam=body_cam,
        face_idx=face_idx,
    )


def uv_grid(h: int, w: int, device: str):
    u, v = torch.meshgrid(
        torch.linspace(0.5 / w, 1.0 - 0.5 / w, w, device=device),
        torch.linspace(0.5 / h, 1.0 - 0.5 / h, h, device=device),
        indexing="xy",
    )
    return u, v


def erp_uv_grid(h: int, w: int, device: str):
    u, v = uv_grid(h, w, device)
    phi = u * 2.0 * np.pi - np.pi
    theta = -v * np.pi - np.pi / 2.0
    return phi, theta


def equirect_facetype(h: int, w: int):
    """
    0F 1R 2B 3L 4U 5D
    """
    tp = np.roll(np.arange(4).repeat(w // 4)[None, :].repeat(h, 0), 3 * w // 8, 1)

    mask = np.zeros((h, w // 4), dtype=bool)
    idx = np.linspace(-np.pi, np.pi, w // 4) / 4.0
    idx = h // 2 - np.round(np.arctan(np.cos(idx)) * h / np.pi).astype(int)
    for i, j in enumerate(idx):
        mask[:j, i] = True
    mask = np.roll(np.concatenate([mask] * 4, 1), 3 * w // 8, 1)

    tp[mask] = 4
    tp[np.flip(mask, 0)] = 5
    return tp.astype(np.int32)


@lru_cache(maxsize=32)
def cubmap_mapping(face_w: int, h: int, w: int):
    phi, theta = erp_uv_grid(h, w, "cpu")
    phi = phi.numpy()
    theta = theta.numpy()

    tp = equirect_facetype(h, w)
    coor_x = np.zeros((h, w), dtype=np.float32)
    coor_y = np.zeros((h, w), dtype=np.float32)

    for i in range(4):
        mask = tp == i
        coor_x[mask] = 0.5 * np.tan(phi[mask] - np.pi * i / 2.0)
        coor_y[mask] = -0.5 * np.tan(theta[mask]) / np.cos(phi[mask] - np.pi * i / 2.0)

    mask = tp == 4
    c = 0.5 * np.tan(np.pi / 2.0 - theta[mask])
    coor_x[mask] = c * np.sin(phi[mask])
    coor_y[mask] = c * np.cos(phi[mask])

    mask = tp == 5
    c = 0.5 * np.tan(np.pi / 2.0 - np.abs(theta[mask]))
    coor_x[mask] = c * np.sin(phi[mask])
    coor_y[mask] = -c * np.cos(phi[mask])

    coor_x = (np.clip(coor_x, -0.5, 0.5) + 0.5) * face_w
    coor_y = (np.clip(coor_y, -0.5, 0.5) + 0.5) * face_w
    return tp.astype(np.float32), coor_x.astype(np.float32), coor_y.astype(np.float32)


def sample_cubefaces(
    cube_faces: torch.Tensor,
    tp: torch.Tensor,
    coor_y: torch.Tensor,
    coor_x: torch.Tensor,
) -> torch.Tensor:
    """
    Args:
        cube_faces: (B, 6, C, face_h, face_w)
        tp/coor_y/coor_x: ERP mapping tensors generated by ``cubmap_mapping``.

    Returns:
        pano: (B, C, H_erp, W_erp)
    """
    pad_ud = torch.stack([
        torch.stack([cube_faces[:, 5, :, 0, :], cube_faces[:, 4, :, -1, :]], -2),
        torch.stack([cube_faces[:, 5, :, :, -1], cube_faces[:, 4, :, :, -1].flip(-1)], -2),
        torch.stack([cube_faces[:, 5, :, -1, :].flip(-1), cube_faces[:, 4, :, 0, :].flip(-1)], -2),
        torch.stack([cube_faces[:, 5, :, :, 0].flip(-1), cube_faces[:, 4, :, :, 0]], -2),
        torch.stack([cube_faces[:, 0, :, 0, :], cube_faces[:, 2, :, 0, :].flip(-1)], -2),
        torch.stack([cube_faces[:, 2, :, -1, :].flip(-1), cube_faces[:, 0, :, -1, :]], -2),
    ], 1)
    cube_faces = torch.cat([cube_faces, pad_ud], -2)

    pad_lr = torch.stack([
        torch.stack([cube_faces[:, 1, :, :, 0], cube_faces[:, 3, :, :, -1]], -1),
        torch.stack([cube_faces[:, 2, :, :, 0], cube_faces[:, 0, :, :, -1]], -1),
        torch.stack([cube_faces[:, 3, :, :, 0], cube_faces[:, 1, :, :, -1]], -1),
        torch.stack([cube_faces[:, 0, :, :, 0], cube_faces[:, 2, :, :, -1]], -1),
        F.pad(
            torch.stack([cube_faces[:, 1, :, 0, :].flip(-1), cube_faces[:, 3, :, 0, :]], -1),
            (0, 0, 1, 1),
            "constant",
            0,
        ),
        F.pad(
            torch.stack([cube_faces[:, 1, :, -2, :], cube_faces[:, 3, :, -2, :].flip(-1)], -1),
            (0, 0, 1, 1),
            "constant",
            0,
        ),
    ], 1)
    cube_faces = torch.cat([cube_faces, pad_lr], -1)
    cube_faces = torch.roll(cube_faces, 1, -1)
    cube_faces = torch.roll(cube_faces, 1, -2)

    batch_size, num_faces, _, face_h, face_w = cube_faces.shape
    cube_faces = cube_faces.permute(0, 2, 1, 3, 4).reshape(
        batch_size, cube_faces.shape[2], num_faces * face_h, face_w
    )

    coor_x = (coor_x + 1.0) / face_w * 2.0 - 1.0
    coor_y = ((coor_y + 1.0 + tp * face_h) / face_h / num_faces) * 2.0 - 1.0
    grid = torch.stack([coor_x, coor_y], -1).to(cube_faces.device, dtype=cube_faces.dtype)
    grid = grid.unsqueeze(0).expand(batch_size, -1, -1, -1)
    pano = F.grid_sample(cube_faces, grid, mode="bilinear", align_corners=False)
    return pano


def aggregate_face_n_touched(
    rendered_faces: List[Optional[dict]],
    num_gaussians: int,
    device: torch.device,
) -> torch.Tensor:
    total = torch.zeros(num_gaussians, dtype=torch.long, device=device)
    for pkg in rendered_faces:
        if pkg is None:
            continue
        total = total + pkg["n_touched"]
    return total


def render_panoramic(
    body_cam,
    gaussians,
    pipeline_params,
    background: torch.Tensor,
) -> dict:
    """
    Render 6 cube faces with the provided cubemap rotations, then stitch them
    back to ERP for RGB / depth / alpha using the same mapping function.
    """

    if body_cam.original_image is not None:
        erp_h = int(body_cam.original_image.shape[1])
        erp_w = int(body_cam.original_image.shape[2])
    else:
        erp_h = int(body_cam.image_height)
        erp_w = int(body_cam.image_width)

    face_w = body_cam.face_w
    device = background.device
    dtype = background.dtype

    rendered_faces: List[Optional[dict]] = []
    face_images_list: List[torch.Tensor] = []
    face_depths_list: List[torch.Tensor] = []
    face_alphas_list: List[torch.Tensor] = []

    for face_idx in range(6):

        face_cam = _build_face_camera(body_cam, face_idx)
        pkg = render(face_cam, gaussians, pipeline_params, background)
        rendered_faces.append(pkg)

        if pkg is None:
            face_images_list.append(torch.zeros(3, face_w, face_w, device=device, dtype=dtype))
            face_depths_list.append(torch.zeros(1, face_w, face_w, device=device, dtype=dtype))
            face_alphas_list.append(torch.zeros(1, face_w, face_w, device=device, dtype=dtype))
            continue

        face_img = pkg["render"].clamp(0.0, 1.0)
        face_depth = pkg["depth"]
        face_alpha = pkg["opacity"].clamp(0.0, 1.0)

        if face_depth.dim() == 2:
            face_depth = face_depth.unsqueeze(0)
        if face_alpha.dim() == 2:
            face_alpha = face_alpha.unsqueeze(0)

        face_images_list.append(face_img)
        face_depths_list.append(face_depth)
        face_alphas_list.append(face_alpha)

    face_imgs = torch.stack(face_images_list, dim=0)
    face_depths = torch.stack(face_depths_list, dim=0)
    face_alphas = torch.stack(face_alphas_list, dim=0)

    tp_np, coor_x_np, coor_y_np = cubmap_mapping(face_w, erp_h, erp_w)
    tp = torch.from_numpy(tp_np).to(device=device, dtype=face_imgs.dtype)
    coor_x = torch.from_numpy(coor_x_np).to(device=device, dtype=face_imgs.dtype)
    coor_y = torch.from_numpy(coor_y_np).to(device=device, dtype=face_imgs.dtype)

    erp_render = sample_cubefaces(face_imgs.unsqueeze(0), tp, coor_y, coor_x).squeeze(0)
    erp_depth = sample_cubefaces(face_depths.unsqueeze(0), tp, coor_y, coor_x).squeeze(0)
    erp_alpha = sample_cubefaces(face_alphas.unsqueeze(0), tp, coor_y, coor_x).squeeze(0)

    n_touched = aggregate_face_n_touched(
        rendered_faces, gaussians.get_xyz.shape[0], device=device
    )
    valid_pkgs = [pkg for pkg in rendered_faces if pkg is not None]
    if valid_pkgs:
        radii = torch.stack([pkg["radii"] for pkg in valid_pkgs], dim=0).max(dim=0).values
        visibility_filter = torch.zeros_like(valid_pkgs[0]["visibility_filter"])
        for pkg in valid_pkgs:
            visibility_filter = visibility_filter | pkg["visibility_filter"]
        # Densification expects a single screen-space tensor. The first face keeps
        # gradients live while radii/visibility aggregate all cube faces.
        viewspace_points = valid_pkgs[0]["viewspace_points"]
    else:
        radii = torch.zeros(gaussians.get_xyz.shape[0], device=device)
        visibility_filter = torch.zeros(
            gaussians.get_xyz.shape[0], dtype=torch.bool, device=device
        )
        viewspace_points = torch.zeros_like(gaussians.get_xyz).requires_grad_(True)

    return {
        "render": erp_render,
        "gs_only": erp_render,
        "sky_bg_only": torch.zeros_like(erp_render),
        "sky_bg_alpha": torch.zeros_like(erp_alpha),
        "depth": erp_depth,
        "opacity": erp_alpha,
        "alpha": erp_alpha,
        "rendered_faces": rendered_faces,
        "face_imgs": face_imgs,
        "face_depths": face_depths,
        "face_alphas": face_alphas,
        "n_touched": n_touched,
        "viewspace_points": viewspace_points,
        "visibility_filter": visibility_filter,
        "radii": radii,
    }


def render_panorama_for_config(
    body_cam,
    gaussians,
    pipeline_params,
    background: torch.Tensor,
    config=None,
    theta=None,
    rho=None,
    get_flag: bool = False,
    metric_map: torch.Tensor | None = None,
    skip_erp_sky_bg: bool = False,
) -> dict:
    """Render a PanoramaCamera using the configured panoramic baseline path."""
    mode = "erp_direct"
    if config is not None:
        mode = config.get("Training", {}).get("panorama_render_mode", "erp_direct")
    if mode == "cubemap_stitch":
        return render_panoramic(body_cam, gaussians, pipeline_params, background)
    if mode == "pfgs360_gsplat":
        from backend.legacy_360gs.utils.pfgs360_renderer import render_pfgs360_erp

        return render_pfgs360_erp(
            body_cam,
            gaussians,
            background,
            theta=theta,
            rho=rho,
            get_flag=get_flag,
            metric_map=metric_map,
            skip_erp_sky_bg=skip_erp_sky_bg,
        )
    return render_erp_direct(
        body_cam,
        gaussians,
        background,
        theta=theta,
        rho=rho,
        get_flag=get_flag,
        metric_map=metric_map,
        skip_erp_sky_bg=skip_erp_sky_bg,
    )


def _get_body_cam_sky_mask(body_cam, H: int, W: int, device, dtype):
    sky_mask = getattr(body_cam, "erp_sky_mask", None)
    if sky_mask is not None:
        if isinstance(sky_mask, torch.Tensor):
            sky_mask = sky_mask.to(device=device, dtype=torch.bool)
        else:
            sky_mask = torch.from_numpy(np.asarray(sky_mask).astype(bool)).to(device=device)
        if sky_mask.ndim == 2:
            sky_mask = sky_mask.unsqueeze(0)
        return sky_mask.view(1, H, W)

    region_masks = getattr(body_cam, "erp_region_masks", None) or {}
    region_sky = region_masks.get("sky", None)
    if region_sky is not None:
        if isinstance(region_sky, torch.Tensor):
            region_sky = region_sky.to(device=device, dtype=torch.bool)
        else:
            region_sky = torch.from_numpy(np.asarray(region_sky).astype(bool)).to(device=device)
        if region_sky.ndim == 2:
            region_sky = region_sky.unsqueeze(0)
        return region_sky.view(1, H, W)

    mono = getattr(body_cam, "mono_depth", None)
    if mono is None:
        return None
    mono = torch.from_numpy(np.asarray(mono).astype(np.float32)).to(device=device, dtype=dtype)
    if mono.ndim == 2:
        mono = mono.unsqueeze(0)
    if mono.shape[-2:] != (H, W):
        return None
    sky_threshold = float(getattr(body_cam, "erp_sky_depth_threshold", 99.9))
    return mono >= sky_threshold


def compose_erp_sky_background(gs_rgb, sky_bg_rgb, sky_mask, sky_alpha):
    if sky_bg_rgb is None or sky_mask is None:
        zeros_alpha = torch.zeros((1, gs_rgb.shape[1], gs_rgb.shape[2]), device=gs_rgb.device, dtype=gs_rgb.dtype)
        return gs_rgb, torch.zeros_like(gs_rgb), zeros_alpha
    if sky_mask.ndim == 2:
        sky_mask = sky_mask.unsqueeze(0)
    sky_mask_f = sky_mask.to(device=gs_rgb.device, dtype=gs_rgb.dtype).clamp(0.0, 1.0)
    if not torch.is_tensor(sky_alpha):
        alpha = torch.full(
            (1, gs_rgb.shape[1], gs_rgb.shape[2]),
            float(sky_alpha),
            device=gs_rgb.device,
            dtype=gs_rgb.dtype,
        )
    else:
        alpha = sky_alpha.to(device=gs_rgb.device, dtype=gs_rgb.dtype)
        if alpha.ndim == 2:
            alpha = alpha.unsqueeze(0)
        if alpha.shape[0] != 1:
            alpha = alpha[:1]
    alpha = (alpha * sky_mask_f).clamp(0.0, 1.0)
    bg_only = sky_bg_rgb.to(device=gs_rgb.device, dtype=gs_rgb.dtype) * sky_mask_f
    final = gs_rgb * (1.0 - alpha) + bg_only * alpha
    return final, bg_only, alpha


# ---------------------------------------------------------------------------
# Direct ERP rendering (single-kernel, differentiable w.r.t. pose + depth)
# ---------------------------------------------------------------------------

def render_erp_direct(
    body_cam,
    gaussians,
    background: torch.Tensor,
    theta=None,
    rho=None,
    get_flag: bool = False,
    metric_map: torch.Tensor | None = None,
    skip_erp_sky_bg: bool = False,
) -> dict:
    """Render an ERP panoramic image using GaussianRasterizerERP directly.

    Unlike render_panoramic() which stitches six pinhole cube-face renders,
    this function calls GaussianRasterizerERP once with the body camera's
    world-view transform.  The result supports:

      * Analytical gradients for cam_rot_delta / cam_trans_delta (theta/rho).
      * Full-sphere visibility (no z > 0 frustum culling).
      * Radial depth (||p_C||) for correct metric depth supervision.
      * viewspace_points.grad for Gaussian densification statistics.

    Args:
        body_cam:   PanoramaCamera (or any camera with image_height/width,
                    world_view_transform, camera_center, cam_rot_delta,
                    cam_trans_delta).
        gaussians:  GaussianModel.
        background: (3,) float32 CUDA tensor.
        theta:      (1, 3) rotation delta override; if None, uses
                    body_cam.cam_rot_delta.unsqueeze(0).
        rho:        (1, 3) translation delta override; if None, uses
                    body_cam.cam_trans_delta.unsqueeze(0).
        skip_erp_sky_bg: When True, skip learnable ERP sky background composite
                    (pure Gaussian image in ``render``). Used during map init so
                    sky Gaussians are optimized against GT without BG blending.

    Returns:
        dict with keys:
            "render"           鈥?(C, H, W) rendered colour.
            "depth"            鈥?(1, H, W) rendered radial depth.
            "opacity"          鈥?(1, H, W) rendered opacity / alpha.
            "alpha"            鈥?alias for "opacity".
            "radii"            鈥?(P,) int32 per-Gaussian 2D radii.
            "n_touched"        鈥?(P,) int32 number of pixels touched.
            "viewspace_points" 鈥?(P, 3) means2D tensor; .grad gives
                                 dL/d(u,v) after backward, used for
                                 Gaussian densification.
            "visibility_filter"鈥?(P,) bool, True for visible Gaussians.
    """
    if getattr(gaussians, "map_mode", None) == "anchor_scaffold_panorama":
        from backend.legacy_360gs.gaussian_splatting.gaussian_renderer.pano_scaffold_renderer import (
            render_pano_scaffold_erp,
        )

        return render_pano_scaffold_erp(
            body_cam,
            gaussians,
            background,
            theta=theta,
            rho=rho,
            get_flag=get_flag,
            metric_map=metric_map,
            skip_erp_sky_bg=skip_erp_sky_bg,
        )

    try:
        from diff_gaussian_rasterization import (
            GaussianRasterizationSettingsERP,
            GaussianRasterizerERP,
        )
    except ImportError as exc:
        raise ImportError(
            "diff_gaussian_rasterization with ERP support not found. "
            "Compile submodules/diff-gaussian-rasterization with `pip install -e .`"
        ) from exc

    H = int(body_cam.image_height)
    W = int(body_cam.image_width)

    settings = GaussianRasterizationSettingsERP(
        image_height=H,
        image_width=W,
        bg=background,
        scale_modifier=1.0,
        viewmatrix=body_cam.world_view_transform,
        sh_degree=gaussians.active_sh_degree,
        campos=body_cam.camera_center,
        prefiltered=False,
        debug=False,
        get_flag=bool(get_flag),
        metric_map=None,
    )
    rasterizer = GaussianRasterizerERP(raster_settings=settings)

    means3D = gaussians.get_xyz
    # Dummy 2D means: .grad after backward gives dL/d(u,v) per Gaussian,
    # used for Gaussian densification stats.
    #
    # ERP stores mean2D in pixel coordinates (range [0, W] / [0, H]), while
    # pinhole stores mean2D in NDC (range [-1, 1]).  The CUDA backward writes
    # dL/d(pixel) to means2D.grad, which is (2/W) times smaller than the
    # pinhole dL/d(NDC) for the same physical gradient signal.  With W=2048
    # this is a ~1000脳 discrepancy, so densify_grad_threshold = 0.0002 would
    # never fire for ERP.  The hook below rescales the gradient back to
    # NDC-equivalent units so the existing threshold works correctly.
    means2D = torch.zeros_like(means3D, requires_grad=True)
    means2D.register_hook(
        lambda g: g * torch.tensor([W / 2.0, H / 2.0, 1.0], device=g.device)
    )

    if theta is None:
        theta = body_cam.cam_rot_delta.unsqueeze(0)   # (1, 3)
    if rho is None:
        rho = body_cam.cam_trans_delta.unsqueeze(0)   # (1, 3)

    metric_map_flat = None
    if metric_map is not None:
        metric_map_t = metric_map.to(device=means3D.device)
        if metric_map_t.ndim == 3:
            metric_map_t = metric_map_t.squeeze(0)
        metric_map_t = metric_map_t.to(dtype=torch.int32)
        if metric_map_t.shape != (H, W):
            raise ValueError(
                f"metric_map shape mismatch: expected {(H, W)}, got {tuple(metric_map_t.shape)}"
            )
        metric_map_flat = metric_map_t.contiguous().view(-1)
    elif get_flag:
        metric_map_flat = torch.zeros(H * W, dtype=torch.int32, device=means3D.device)

    rasterizer.raster_settings = rasterizer.raster_settings._replace(metric_map=metric_map_flat)

    rendered, radii, depth, opacity, n_touched, accum_metric_counts = rasterizer(
        means3D=means3D,
        means2D=means2D,
        opacities=gaussians.get_opacity,
        shs=gaussians.get_features,
        scales=gaussians.get_scaling,
        rotations=gaussians.get_rotation,
        theta=theta,
        rho=rho,
    )

    if depth.dim() == 2:
        depth = depth.unsqueeze(0)
    if opacity.dim() == 2:
        opacity = opacity.unsqueeze(0)

    gs_only = rendered
    sky_bg_only = torch.zeros_like(rendered)
    sky_bg_alpha = torch.zeros_like(opacity)
    _bg_on = bool(
        getattr(gaussians, "config", {}).get("Training", {}).get("enable_erp_sky_background", False)
    )
    if _bg_on and not skip_erp_sky_bg:
        sky_bg = gaussians.get_erp_sky_background(body_cam)
        sky_mask = _get_body_cam_sky_mask(
            body_cam, H, W, device=rendered.device, dtype=rendered.dtype
        )
        alpha_mode = str(
            gaussians.config.get("Training", {}).get("erp_sky_bg_alpha_mode", "fixed")
        ).lower()
        alpha_val = float(
            gaussians.config.get("Training", {}).get("erp_sky_bg_alpha", 0.65)
        )
        if alpha_mode == "opacity":
            alpha_src = (1.0 - opacity.clamp(0.0, 1.0)) * alpha_val
        else:
            alpha_src = alpha_val
        rendered, sky_bg_only, sky_bg_alpha = compose_erp_sky_background(
            rendered, sky_bg, sky_mask, alpha_src
        )

    visibility_filter = radii > 0

    return {
        "render": rendered,
        "gs_only": gs_only,
        "sky_bg_only": sky_bg_only,
        "sky_bg_alpha": sky_bg_alpha,
        "depth": depth,
        "opacity": opacity,
        "alpha": opacity,
        "radii": radii,
        "n_touched": n_touched,
        "accum_metric_counts": accum_metric_counts,
        "viewspace_points": means2D,
        "visibility_filter": visibility_filter,
    }
