base_config: spherical_selfi_global_gs_slam.yaml

Dataset:
  synthetic: false
  type: ob3d
  dataset_path: /mnt/disk1/lanboyang/Datasets/PFGS360/OB3D/OB3D
  scene: sponza
  split: Non-Egocentric
  erp_resize_height: 504
  erp_resize_width: 1008

WeightsAndBiases:
  enabled: true
  project: 360Droid-splat
  mode: online
  run_name: spherical_selfi_global_ob3d_sponza_nonegocentric_posefix_voxel020
  tags: [spherical-selfi, stage2, sim3-graph, fibonacci, posefix, voxel020, ob3d, sponza, non-egocentric]

Visualization:
  enabled: true
  save_local: true
  log_every: 5
  save_kf_opt: true
  kf_opt_log_every: 1

Results:
  save_dir: outputs/spherical_selfi_global_ob3d_sponza_nonegocentric_posefix_voxel020
  kf_render_format: png
